import ProjectDescription

let workspace = Workspace(
    name: "Workspace",
    projects: [
        "App",
        "FeatureA"
    ],
    schemes: [],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
